version: 0.2


phases:
  pre_build:
    commands:

      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 273354648888.dkr.ecr.us-east-1.amazonaws.com/book_catalog
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 273354648888.dkr.ecr.us-east-1.amazonaws.com/inventory_management

  build:
    commands:
      - echo Building Docker images using Docker Compose...
      - chmod +x ./scripts/build-image.sh  # Ensure the script is executable
      - chmod +x ./scripts/push-image.sh
      - ./scripts/build-image.sh  # This script will build the images using Docker Compose
      - ./scripts/push-image.sh  # This script will push the images to ECR

  post_build:
    commands:
      - echo Images have been built and pushed to Amazon ECR successfully.

artifacts:
  files:
    - '**/*'
